### ISSUE TITLE
BungeeCord

### ISSUE THREAD

**Issue by asdasddw14** [NotReference/PremiumLogin#1]
[16:01:57 ERROR]: Error authenticating Wing_Ling with minecraft.net
java.net.UnknownHostException: failed to resolve 'sessionserver.mojang.com' after 3 queries
        at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:925) ~[1.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:8f74df2:323]
        at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:884) ~[1.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:8f74df2:323]
        at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:356) ~[1.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:8f74df2:323]
        at io.netty.resolver.dns.DnsResolveContext.access$600(DnsResolveContext.java:64) ~[1.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:8f74df2:323]
        at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:405) ~[1.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:8f74df2:323]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577) ~[1.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:8f74df2:323]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570) ~[1.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:8f74df2:323]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549) ~[1.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:8f74df2:323]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490) ~[1.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:8f74df2:323]
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615) ~[1.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:8f74df2:323]
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608) ~[1.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:8f74df2:323]
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) ~[1.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:8f74df2:323]
        at io.netty.resolver.dns.DnsQueryContext.tryFailure(DnsQueryContext.java:225) ~[1.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:8f74df2:323]
        at io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:177) ~[1.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:8f74df2:323]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[1.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:8f74df2:323]
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170) ~[1.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:8f74df2:323]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[1.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:8f74df2:323]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[1.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:8f74df2:323]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[1.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:8f74df2:323]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[1.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:8f74df2:323]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[1.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:8f74df2:323]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [/127.0.0.1:53] query via UDP timed out after 5000 milliseconds (no stack trace available)

**Comment by NotReference** [comment]
Do you have legacy connections enabled? The plugin works fine and you get this exception, or you can't login? 

Remember that you have to be Premium (and you have to launch minecraft with official launcher) for be forcelogged.

**Comment by NotReference** [comment]
That is not a my plugin “bug”, but in PremiumLogin 1.6 I tried to increase server performance using async events. If your server has very very little amount of ram, now this is not a big problem but always a problem that can comport server crash etc.. I advice you to Upgrade your ram and the server connection (I think the connection is bad). 

But, if that server was in localhost and you was offline, you must be online for make web http requests to the session server.
